# Generated by Django 4.0.6 on 2022-07-09 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tinta',
            fields=[
                ('idTinta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=255)),
            ],
        ),
    ]
