# Generated by Django 4.0.6 on 2022-07-09 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCure',
            fields=[
                ('idFlashcure', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperaturaMinima', models.IntegerField(verbose_name='temperaturaMinima')),
                ('temperatuMaxima', models.IntegerField(verbose_name='temperatuMaxima')),
                ('temperaturaAtual', models.IntegerField(verbose_name='temperaturaAtual')),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('idMotor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('velocidadeMinima', models.IntegerField(verbose_name='velocidadeMinima')),
                ('velocidadeMaxima', models.IntegerField(verbose_name='velocidadeMaxima')),
                ('velocidadeAtual', models.IntegerField(verbose_name='velocidadeAtual')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tinta',
            options={'ordering': ('cor',)},
        ),
        migrations.AddField(
            model_name='tinta',
            name='FlashCure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessao.flashcure'),
        ),
        migrations.AddField(
            model_name='tinta',
            name='Motor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessao.motor'),
        ),
    ]
