# Generated by Django 4.0.6 on 2022-07-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0004_rename_temperaturaatual_flashcure_tempera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcure',
            name='tempera',
            field=models.IntegerField(verbose_name='temperatura'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='velocidade',
            field=models.IntegerField(verbose_name='velocidade'),
        ),
    ]
