# Generated by Django 4.0.6 on 2022-07-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0005_alter_flashcure_tempera_alter_motor_velocidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcure',
            options={'ordering': ('tempera',)},
        ),
        migrations.AlterModelOptions(
            name='motor',
            options={'ordering': ('velocidade',)},
        ),
    ]
