# Generated by Django 4.0.6 on 2022-07-14 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0006_alter_flashcure_options_alter_motor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoTinta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('velocidadePadrao', models.IntegerField(default=0, verbose_name='Velocidade Padrão')),
                ('temperaturaPadrao', models.IntegerField(default=0, verbose_name='Temperatura Padrão')),
            ],
            options={
                'ordering': ('tipo',),
            },
        ),
        migrations.RemoveField(
            model_name='tinta',
            name='FlashCure',
        ),
        migrations.RemoveField(
            model_name='tinta',
            name='Motor',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='Tinta',
        ),
        migrations.AddField(
            model_name='sessao',
            name='TempFlashCure',
            field=models.IntegerField(default=0, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='velocidadeMotor',
            field=models.IntegerField(default=0, verbose_name='Velocidade'),
        ),
        migrations.DeleteModel(
            name='FlashCure',
        ),
        migrations.DeleteModel(
            name='Motor',
        ),
        migrations.DeleteModel(
            name='Tinta',
        ),
        migrations.AddField(
            model_name='sessao',
            name='tipoTinta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessao.tipotinta'),
        ),
    ]
