# Generated by Django 4.0.6 on 2022-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0007_tipotinta_remove_tinta_flashcure_remove_tinta_motor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='TempFlashCure',
            field=models.IntegerField(default=0, verbose_name='Temperatura ºC.'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='velocidadeMotor',
            field=models.IntegerField(default=0, verbose_name='Velocidade RPM'),
        ),
        migrations.AlterField(
            model_name='tipotinta',
            name='temperaturaPadrao',
            field=models.IntegerField(default=0, verbose_name='Temperatura Padrão RPM'),
        ),
        migrations.AlterField(
            model_name='tipotinta',
            name='tipo',
            field=models.TextField(max_length=200, verbose_name='Tipo Tinta'),
        ),
        migrations.AlterField(
            model_name='tipotinta',
            name='velocidadePadrao',
            field=models.IntegerField(default=0, verbose_name='Velocidade Padrão ºC'),
        ),
    ]
