# Generated by Django 4.0.6 on 2022-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0009_tipotinta_teste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotinta',
            options={'ordering': ('comment',)},
        ),
        migrations.RemoveField(
            model_name='tipotinta',
            name='temperaturaPadrao',
        ),
        migrations.RemoveField(
            model_name='tipotinta',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='tipotinta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='tipotinta',
            name='velocidadePadrao',
        ),
        migrations.AddField(
            model_name='tipotinta',
            name='comment',
            field=models.TextField(max_length=200, null=True, verbose_name='Comentário'),
        ),
    ]
