# Generated by Django 4.0.6 on 2022-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0011_alter_tipotinta_options_remove_tipotinta_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='quantidadeTinta',
            field=models.IntegerField(default=0, verbose_name='Quantidade Tinta ºC.'),
        ),
        migrations.AlterField(
            model_name='tipotinta',
            name='temperaturaPadrao',
            field=models.IntegerField(default=0, verbose_name='Temperatura Padrão ºC'),
        ),
        migrations.AlterField(
            model_name='tipotinta',
            name='velocidadePadrao',
            field=models.IntegerField(default=0, verbose_name='Velocidade Padrão RMP'),
        ),
    ]
