# Generated by Django 4.0.6 on 2022-07-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0012_sessao_quantidadetinta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaSecagem', models.IntegerField(default=100, verbose_name='Temperatura de Secagem °C')),
                ('tempoSecagem', models.IntegerField(default=30, verbose_name='Tempo de Secagem S')),
                ('tipo', models.TextField(default='outro', max_length=200, verbose_name='Tipo da tinta')),
            ],
        ),
        migrations.CreateModel(
            name='BaseProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.TextField(default='branca', max_length=200, verbose_name='cor')),
                ('ordem', models.IntegerField(default=1, verbose_name='ordem')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producao_tipoTinta', to='sessao.base')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeDeCamisetas', models.IntegerField(default=4, verbose_name='quantidade de camisetas')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDeCamisetas', models.IntegerField(default=4, verbose_name='Total de camisetas')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('velocidade', models.IntegerField(default=1, verbose_name='velocidade do motor')),
                ('tempoDeProducao', models.IntegerField(default=30, verbose_name='Tempo de producao')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('base', models.ManyToManyField(related_name='bases', through='sessao.BaseProducao', to='sessao.base')),
            ],
        ),
        migrations.DeleteModel(
            name='Sessao',
        ),
        migrations.DeleteModel(
            name='tipoTinta',
        ),
        migrations.AddField(
            model_name='lote',
            name='producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.producao'),
        ),
        migrations.AddField(
            model_name='baseproducao',
            name='producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producao_tipoTinta', to='sessao.producao'),
        ),
    ]
