# Generated by Django 4.0.6 on 2022-07-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0013_base_baseproducao_lote_producao_delete_sessao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproducao',
            name='ordem',
        ),
    ]
